/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from "./Junofarms.types";
import * as _1 from "./Junofarms.client";
import * as _2 from "./Junofarms.react-query";
export namespace contracts {
  export const Junofarms = { ..._0, ..._1, ..._2 };
}
