/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from "./Junofarms.types";
import * as _1 from "./Junofarms.client";
import * as _2 from "./Junofarms.react-query";
import * as _3 from "./KompleMint.types";
import * as _4 from "./KompleMint.client";
import * as _5 from "./KompleMint.react-query";
import * as _6 from "./KompleToken.types";
import * as _7 from "./KompleToken.client";
import * as _8 from "./KompleToken.react-query";
export namespace contracts {
  export const Junofarms = { ..._0, ..._1, ..._2 };
  export const KompleMint = { ..._3, ..._4, ..._5 };
  export const KompleToken = { ..._6, ..._7, ..._8 };
}
