/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Addr = string;
export interface InstantiateMsg {
  admin?: string | null;
  komple_mint_addr?: string | null;
  whitelisted_collections?: KompleCollection[] | null;
}
export interface KompleCollection {
  addr: Addr;
  id: number;
}
export type ExecuteMsg =
  | {
      start: {};
    }
  | {
      stop: {};
    }
  | {
      till_ground: {
        x: number;
        y: number;
      };
    }
  | {
      water_plant: {
        x: number;
        y: number;
      };
    }
  | {
      harvest: {
        x: number;
        y: number;
      };
    }
  | {
      receive_nft: Cw721ReceiveMsg;
    };
export type Binary = string;
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
}
export type QueryMsg =
  | {
      contract_info: {};
    }
  | {
      get_farm_profile: {
        address: string;
      };
    };
export interface ContractInformationResponse {
  admin: string;
  komple_mint_addr?: string | null;
  whitelisted_collections: KompleCollection[];
}
export type PlantType = "sunflower" | "wheat";
export type SlotType = "meadow" | "field";
export interface FarmProfileDto {
  blocks: number;
  plots: SlotDto[][];
}
export interface SlotDto {
  can_till: boolean;
  plant?: PlantDto | null;
  type: SlotType;
}
export interface PlantDto {
  can_harvest: boolean;
  can_water: boolean;
  created_at: number;
  current_stage: number;
  growth_period: number;
  is_dead: boolean;
  komple?: KomplePlant | null;
  stages: number;
  type: PlantType;
  watered_at: number[];
}
export interface KomplePlant {
  collection_id: number;
  metadata_id: number;
}
